### ISSUE TITLE
test/format sanitizer memory leak

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1736] opened 2015-03-08 22:45 UTC
In Jenkins:

http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/2934/console

The failure is:

```
==62513==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 88 byte(s) in 5 object(s) allocated from:
    #0 0x48e0c9 in calloc (/home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/test/format/t+0x48e0c9)
    #1 0x687a98 in __wt_calloc /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/os_posix/os_alloc.c:39
    #2 0xa92818 in __wt_row_ikey_alloc /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/btree/row_key.c:478
    #3 0xa941c2 in __wt_row_ikey /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/btree/row_key.c:512
    #4 0xa0100d in __split_ref_deepen_move /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/btree/bt_split.c:284
    #5 0x9fe346 in __split_deepen /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/btree/bt_split.c:493
    #6 0x9f094f in __split_parent /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/btree/bt_split.c:1034
    #7 0x9f4835 in __wt_split_multi /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/btree/bt_split.c:1493
    #8 0x5cd7ba in __evict_page_dirty_update /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/evict/evict_page.c:215
    #9 0x5c79de in __wt_evict /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/evict/evict_page.c:109
    #10 0x5a6cba in __wt_evict_page /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/evict/evict_lru.c:660
    #11 0x5aa91f in __wt_evict_lru_page /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/evict/evict_lru.c:1372
    #12 0x5ad4a5 in __wt_cache_wait /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/evict/evict_lru.c:1431
    #13 0xd78ca2 in __wt_cache_full_check /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/include/cache.i:197
    #14 0xd79e4e in __cursor_enter /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/include/cursor.i:63:33
    #15 0xd79026 in __curfile_enter /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/include/cursor.i:96:32
    #16 0xd5a67e in __cursor_func_init /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/include/cursor.i:198:33
    #17 0xd57f4c in __wt_btcur_search /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/btree/bt_cursor.c:308:32
    #18 0xb5b5f3 in __curfile_search /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/../src/cursor/cur_file.c:200
    #19 0x4bf992 in read_row /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/test/format/../../../test/format/ops.c:608
    #20 0x4bd360 in ops /home/jenkins/jenkins/workspace/wiredtiger-test-format-stress-sanitizer/build_posix/test/format/../../../test/format/ops.c:482
    #21 0x3f17e07ee4 in start_thread (/lib64/libpthread.so.0+0x3f17e07ee4)
```

The test format configuration is:

```
############################################
#  RUN PARAMETERS
############################################
abort=0
auto_throttle=1
firstfit=0
bitcnt=1
bloom=1
bloom_bit_count=22
bloom_hash_count=27
bloom_oldest=0
cache=1
checkpoints=1
checksum=uncompressed
chunk_size=8
compaction=0
compression=bzip
data_extend=0
data_source=file
delete_pct=27
dictionary=0
evict_max=5
file_type=row-store
backups=0
huffman_key=0
huffman_value=0
insert_pct=27
internal_key_truncation=1
internal_page_max=17
isolation=snapshot
key_gap=3
key_max=91
key_min=17
leak_memory=0
leaf_page_max=12
logging=0
logging_archive=0
logging_prealloc=1
logging=0
lsm_worker_threads=3
merge_max=20
mmap=1
ops=100000
prefix_compression=1
prefix_compression_min=8
repeat_data_pct=61
reverse=0
rows=100000
runs=1
split_pct=77
statistics=0
statistics_server=0
threads=4
timer=20
value_max=577
value_min=18
wiredtiger_config=
write_pct=10
############################################
```

**Comment by michaelcahill** [comment] 2015-03-09 00:34
duplicate of #1582

**Closed by michaelcahill** 2015-03-09 00:34 UTC
