### ISSUE TITLE
Checkpoint bug

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1546] opened 2015-01-12 20:08 UTC
There seems to be a bug in checkpoint that is appearing. We have seen two recent Jenkins failures (possibly different, but seems unlikely).

First:
http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress/6062

Failure:
```
87: table, row-store
[1421092007:297178][19833:0x7f5e635fe700], t, file:wt.wt, session.checkpoint: ../src/reconcile/rec_write.c, 3203: state == WT_CHILD_MODIFIED
[1421092007:297219][19833:0x7f5e635fe700], t, file:wt.wt, session.checkpoint: aborting WiredTiger library
*** Aborted
```

Configuration file:
```
############################################
#  RUN PARAMETERS
############################################
abort=0
auto_throttle=1
firstfit=0
bitcnt=5
bloom=1
bloom_bit_count=19
bloom_hash_count=6
bloom_oldest=0
cache=27
checkpoints=1
checksum=uncompressed
chunk_size=5
compaction=0
compression=none
data_extend=0
data_source=table
delete_pct=36
dictionary=0
evict_max=1
file_type=variable-length column-store
backups=0
huffman_key=0
huffman_value=0
insert_pct=21
internal_key_truncation=1
internal_page_max=10
isolation=read-uncommitted
key_gap=15
key_max=65
key_min=32
leak_memory=0
leaf_page_max=16
logging=0
logging_archive=0
logging_prealloc=0
logging=0
lsm_worker_threads=3
merge_max=15
mmap=0
ops=100000
prefix_compression=1
prefix_compression_min=1
repeat_data_pct=79
reverse=0
rows=100000
runs=100
split_pct=50
statistics=0
threads=24
timer=0
value_max=2479
value_min=10
wiredtiger_config=
write_pct=53
############################################
```

Second:

http://build.wiredtiger.com:8080/job/wiredtiger/3817/

test/checkpoint failed with mismatching data ranges.

**Comment by sueloverso** [comment] 2015-01-12 20:13
@agorrod The first is duplicate of #1525.  The second is a duplicate of #1521.  They don't yet appear related to each other.   I'm closing this one.

**Closed by sueloverso** 2015-01-12 20:13 UTC
